apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
      command:
        - sh
      args:
        - -c
        - |
          apk add --no-cache git && exec /usr/local/bin/jenkins-agent
      workingDir: /home/jenkins/agent
      resources:
        requests:
          cpu: 200m
          memory: 350Mi
          ephemeral-storage: 150Mi
        limits:
          cpu: 512m
          memory: 512Mi
          ephemeral-storage: 200Mi
      securityContext:
        privileged: true

    - name: shell
      image: node:slim
      command:
        - sh
      args:
        - -c
        - |
          apt-get update && apt-get install -y git && sleep infinity
      resources:
        requests:
          memory: 600Mi
          cpu: "1"
          ephemeral-storage: 500Mi
        limits:
          memory: 1000Mi
          cpu: "1.5"
          ephemeral-storage: 2000Mi
