apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
      workingDir: /home/jenkins/agent
      resources:
        requests:
          cpu: 200m
          memory: 350Mi
          ephemeral-storage: 150Mi
        limits:
          cpu: 512m
          memory: 512Mi
          ephemeral-storage: 200Mi
      securityContext:
        privileged: true
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
          readOnly: false
    - name: shell
      image: node:18
      command:
        - sh
      args:
        - -c
        - |
          apt-get update && apt-get install -y git curl && 
          git --version && 
          git config --global --add safe.directory '*' &&
          echo "Git installed and configured successfully" && 
          sleep infinity
      workingDir: /home/jenkins/agent
      resources:
        requests:
          memory: 600Mi
          cpu: "1"
          ephemeral-storage: 500Mi
        limits:
          memory: 1000Mi
          cpu: "1.5"
          ephemeral-storage: 2000Mi
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
          readOnly: false
  nodeSelector:
    kubernetes.io/os: linux
  restartPolicy: Never
  volumes:
    - name: workspace-volume
      emptyDir: {}
